export const TEMPLATES_GET_TEMPLATES_BEGIN = 'TEMPLATES_GET_TEMPLATES_BEGIN';
export const TEMPLATES_GET_TEMPLATES_SUCCESS = 'TEMPLATES_GET_TEMPLATES_SUCCESS';
export const TEMPLATES_GET_TEMPLATES_FAILURE = 'TEMPLATES_GET_TEMPLATES_FAILURE';
export const TEMPLATES_GET_TEMPLATES_DISMISS_ERROR = 'TEMPLATES_GET_TEMPLATES_DISMISS_ERROR';
